// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArcGISMap: typeof import('./components/ArcGISMap.vue')['default']
    EditPlacesForm: typeof import('./components/EditPlacesForm.vue')['default']
    NoteForm: typeof import('./components/NoteForm.vue')['default']
    NoteList: typeof import('./components/NoteList.vue')['default']
    PlacesForm: typeof import('./components/PlacesForm.vue')['default']
    PlacesList: typeof import('./components/PlacesList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
